name: Deploy website to server

on:
  push:
    branches:
      - main
    paths:
      - 'public/**'

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v6

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/